apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-website-deployment
  labels:
    app: static-website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: static-website
  template:
    metadata:
      labels:
        app: static-website
    spec:
      containers:
      - name: static-website
        image: your-dockerhub-username/static-website:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: static-website-service
spec:
  type: LoadBalancer
  selector:
    app: static-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
